server:
  port: 9030
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community_content_center?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    hikari:
      username: root
      password: wen175924
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.72.130
    port: 6379
    password: 123456
  cloud:
    # nacos
    nacos:
      discovery:
        server-addr: localhost:8848
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
        bindings:
          output:
            producer:
              # 开启支持本地事务
              transactional: true
              # @AddBonusTransactionListener(txProducerGroup = "AddBonusTransaction-Group") 相一致
              group: AddBonusTransaction-Group
      bindings:
        output:
          #用来指定 topic
          destination:
            AddBonus-Topic

  application:
    name: content-center
  main:
    allow-bean-definition-overriding: true

# 数据库映射 下划线 <--> 驼峰
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true


#JWT密钥
jwt:
  secret: wwwbanmingixyzcommunity-plus123456789abc
  # 有效期，单位秒，默认1周
  expire-time-in-second: 604800