server:
  port: 9030
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community_content_center?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    hikari:
      username: root
      password: wen175924
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    # nacos
    nacos:
      discovery:
        server-addr: localhost:8848

  application:
    name: content-center
  main:
    allow-bean-definition-overriding: true

# 数据库映射 下划线 <--> 驼峰
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true