server:
  port: 9000
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.72.130:8848
        # 路由网关配置
    gateway:
      # 设置与服务注册发现组件结合，这样可以采用服务名的路由策略
      discovery:
        locator:
          enabled: true
      routes:
        #用户中心
        - id: USER-CENTER
          uri: lb://user-center
          predicates:
            # 路径匹配
            - Path=/users/**
        #内容中心
        - id: CONTENT-CENTER
          uri: lb://content-center
          predicates:
            # 路径匹配
            - Path=/category/**,/articles/**,/admin/articles/**,/comment/**
        #云中心
        - id: CLOUD-CENTER
          uri: lb://cloud-center
          predicates:
            # 路径匹配
            - Path=/upload/**
