server:
  port: 9040
spring:
  servlet:
    multipart:
      max-file-size: 10MB
  cloud:
    # nacos
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: cloud-center
  main:
    allow-bean-definition-overriding: true



