server:
  port: 9010
spring:
  datasource:
    url: jdbc:mysql://192.168.72.130:3306/community_user_center?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    hikari:
      username: root
      password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.72.130
    port: 6379
    password: 123456
  cloud:
    # nacos
    nacos:
      discovery:
        server-addr: 192.168.72.130:8848
    stream:
      rocketmq:
        binder:
          name-server: 192.168.72.130:9876
      bindings:
        # 验证码
        checkCode-output:
          destination: CheckCode-Topic
         # 积分
        addBonus-input:
          destination:
            AddBonus-Topic
          group:
            AddBonus-Group

  application:
    name: user-center
  main:
    allow-bean-definition-overriding: true

# 数据库映射 下划线 <--> 驼峰
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true


#JWT密钥
jwt:
  secret: wwwbanmingixyzcommunity-plus123456789abc
  # 有效期，单位秒，默认1周
  expire-time-in-second: 604800

