server:
  port: 9010
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community_user_center?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    hikari:
      username: root
      password: wen175924
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    # nacos
    nacos:
      discovery:
        server-addr: localhost:8848

  application:
    name: user-center
  main:
    allow-bean-definition-overriding: true

# 数据库映射 下划线 <--> 驼峰
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true


#JWT密钥
jwt:
  secret: wwwbanmingixyzcommunity-plus123456789abc
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600